name: Deployment
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npx npx gh-pages -d dist
