name: Fetch Data
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-and-commit:
    permissions: write-all
    # permissions:
    #   contents: read
    #   pull-requests: read
    #   commits: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Fetch
        run: ./fetch_data.ts

      - name: Commit
        run: |
          git commit -am 'fetch data'
          git push
